In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy 

# Basic Operations

In [2]:
import numpy as np

In [11]:
a = np.array([1,3,3])

In [12]:
print(a)

[1 3 3]


In [5]:
type(a)

numpy.ndarray

In [7]:
b  = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(b)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [8]:
type(b)

numpy.ndarray

In [17]:
a = np.array([1,2,3], dtype= str)
print(a)


['1' '2' '3']


In [18]:
a = np.array([6.5,2,3], dtype= int)
print(a)


[6 2 3]


## Length of an array


In [19]:
len(a)

3

In [22]:
b = np.array([[1,2,3], [4,5,6],[6,7,8]])

print(b)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [23]:
len(b)

3

In [27]:
c = np.array([[1,2,3,5], [4,5,6,7],[7,8,9,10]])
print(c)

[[ 1  2  3  5]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [26]:
len(c)

3

### Get the diamension of array

In [24]:
a.ndim

1

In [25]:
b.ndim

2

In [28]:
c.ndim

2

## Shape of array

In [33]:
a = np.array([1,"2",3])
print(a)
a.shape

['1' '2' '3']


(3,)

In [39]:
b = np.array([[1.0,2,3,4], [4,5,6,8],[4,5,6,8]])
print(b)
b.shape

[[1. 2. 3. 4.]
 [4. 5. 6. 8.]
 [4. 5. 6. 8.]]


(3, 4)

In [40]:
c.shape

(3, 4)

## data type of elements in array

In [35]:
a.dtype

dtype('<U21')

In [41]:
b.dtype

dtype('float64')

In [38]:
c.dtype

dtype('int64')

## Accessing / Changing specific elements in array

In [42]:
a = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12],[71,82,19,110,101,22]])
print(a)

[[  1   2   3   4   5   6]
 [  7   8   9  10  11  12]
 [ 71  82  19 110 101  22]]


In [51]:
a[0,2] = 3
a

array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 71,  82,  19, 110, 101,  22]])

In [52]:
a[1,0]

7

In [53]:
a[2,0]=85
a

array([[  1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12],
       [ 85,  82,  19, 110, 101,  22]])

In [54]:
a[2,:]

array([ 85,  82,  19, 110, 101,  22])

In [56]:
a[:,2]

array([ 3,  9, 19])

In [56]:
a[1,:]

array([ 7,  8,  9, 10, 11, 12])

In [34]:
a[:,0]

array([ 1,  7, 71])

In [58]:
a[:,2]

array([3, 9])

In [57]:
a[:0]

array([], shape=(0, 6), dtype=int64)

In [38]:
a[1,2]=90
print(a)

[[  1   2   3   4  30   6]
 [  7   8  90  10  11  12]
 [ 71  82  19 110 101  22]]


## Special Initialising Methods in Numpy

### Zeros / Ones Methods

In [53]:
new_arr = np.zeros((4,5), dtype=int)
new_arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [50]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [65]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [66]:
np.zeros((3,3), dtype = str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [56]:
np.full((3,3),"F", dtype = str)

array([['F', 'F', 'F'],
       ['F', 'F', 'F'],
       ['F', 'F', 'F']], dtype='<U1')

In [58]:
np.random.rand(3,3)

array([[0.04999277, 0.1361148 , 0.9261675 ],
       [0.07094658, 0.76375023, 0.44965615],
       [0.04474269, 0.27353811, 0.89166906]])

In [59]:
np.random.randint(1,20, size=(3,3))

array([[ 7, 13,  3],
       [ 1, 10, 18],
       [13,  3, 19]])

In [61]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Extract First 3 rows of the last 5 columns of the given array 
#### I/P : 
      [[1 2 3 4 5 6 7 8]
       [1 2 3 4 5 6 7 8]
       [1 2 3 4 5 6 7 8]
       [1 2 3 4 5 6 7 8]
       [1 2 3 4 5 6 7 8]]
#### O/P:
     [[4,5,6,7,8]
     [4,5,6,7,8]
     [4,5,6,7,8]]

In [68]:
a = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
print(a)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [70]:
a[:3,-5:]

array([[4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8],
       [4, 5, 6, 7, 8]])

## Arithmetic Operations with NumPy - Maths + Stats

In [61]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [63]:
a+10

array([11, 12, 13, 14])

In [64]:
a = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
print(a)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [65]:
a-2

array([[-1,  0,  1,  2,  3,  4,  5,  6],
       [-1,  0,  1,  2,  3,  4,  5,  6],
       [-1,  0,  1,  2,  3,  4,  5,  6],
       [-1,  0,  1,  2,  3,  4,  5,  6],
       [-1,  0,  1,  2,  3,  4,  5,  6]])

In [69]:
#DO it for -, /, *, //, ** - ALmost all the operations are satisfied

a**3

array([ 1,  8, 27, 64])

In [67]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [92]:
a.min()

1

In [93]:
a.max()

4

In [96]:
np.max(a)

4

In [71]:
np.mean(a)

2.5

In [77]:
a = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,-3,4,5,69,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,76,8]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 1  2  3  4  5  6  7  8]
 [ 1  2 -3  4  5 69  7  8]
 [ 1  2  3  4  5  6  7  8]
 [ 1  2  3  4  5  6 76  8]]


In [79]:
np.min(a)

-3

In [80]:
np.mean(a)

7.65

In [98]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
np.max(a)

8

In [100]:
np.mean(a)

4.5

In [81]:
np.max(a, axis=1)


array([ 8,  8, 69,  8, 76])

In [82]:
np.max(a, axis=0)


array([ 1,  2,  3,  4,  5, 69, 76,  8])

## Reshaping arrays

In [84]:

arr = np.array([18, 20, 13, 14, 15, 16, 17, 18, 19, 10, 11,12])

arr_2d = arr.reshape(3,4)

print(arr_2d)

[[18 20 13 14]
 [15 16 17 18]
 [19 10 11 12]]


In [92]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12,13,14,15,16,17,18,19,20,21,22,23,24])

arr_3d = arr.reshape(3,4,2)

print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


## Unknown Dimension

In [93]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12,13,14,15,16,17,18,19,20,21,22,23,24])

newarr = arr.reshape(2,4,-1)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
